# Generated by Django 5.0.7 on 2024-07-29 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_cars_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='iamge',
            field=models.ImageField(blank=True, null=True, upload_to='cars'),
        ),
    ]
