# Generated by Django 5.0.7 on 2024-08-02 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_cars_iamge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars',
            old_name='iamge',
            new_name='image',
        ),
    ]
