# Generated by Django 5.0.7 on 2024-09-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_carinventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
